# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - develop
 


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
            - uses : actions/checkout@v2
              with:
                fetch-depth: 0 
                
            - name: Derive from branch name
              run: |
                  # do custom parsing of your code / date to derive a branch from
                  PR_BRANCH_FROM=release-v$(cat VERSION)
                  export "PULL_REQUEST_FROM_BRANCH=${PR_BRANCH_FROM}" >> $GITHUB_ENV

            - name: Create Pull Request
              uses: zsfVishnu-d11/pull-request-action@1.0.13
              env:
                PULL_REQUEST_BRANCH: "master"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#                 PULL_REQUEST_FROM_BRANCH: "develop"
                PASS_ON_ERROR: true
                PULL_REQUEST_BODY: "🚀 Opening a pull request for this branch"
